t1

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -46,7 +46,8 @@ jobs:
           paths:
             - code
 
-  deploy:
+  # Demonstration of deployment in 'force-push' mode.
+  deploy-force-push:
     <<: *container_config
     steps:
       - attach_workspace:
@@ -57,47 +58,146 @@ jobs:
       - *step_setup_git
       - checkout
 
+      # Test file will have a consistent name between deployments, but
+      # the contents will be added to on each deployment to simulate
+      # changes in the source repository.
       - run:
-          name: Demonstration of deployment in 'force-push' mode.
+          name: Prepare test file.
           command: |
-            TEST_FILE="test-file-force-push-circleci-$(date "+%Y%m%d-%H%M%S").txt"
-            touch $TEST_FILE
+            TEST_FILE="test-file--force-push--circleci--${CIRCLE_BRANCH}.txt"
+            echo "Deployment 1 for branch ${CIRCLE_BRANCH}" >> $TEST_FILE
+            date "+%Y%m%d-%H%M%S" >> $TEST_FILE
 
+      - run:
+          name: Deployment 1
+          command: |
             vendor/bin/robo artifact \
               git@github.com:drevops/git-artifact-destination.git \
-              --branch=mode-force-push-circleci--[branch] \
+              --branch=mode--force-push--circleci--[branch] \
               --mode=force-push \
-              --report=$HOME/report-mode-force-push.txt \
-              --push
+              --report=$HOME/report--mode--force-push.txt \
+              --push \
+              --debug
 
-            DEPLOY_BRANCH=$(sed -n 's/Remote branch://p' $HOME/report-mode-force-push.txt | sed 's/ //g')
-            echo "Deployed to $DEPLOY_BRANCH"
+            DEPLOYED_BRANCH=$(sed -n 's/Remote branch://p' $HOME/report--mode--force-push.txt | sed 's/ //g')
+            echo "Deployed to $DEPLOYED_BRANCH"
             echo
-            echo "See https://github.com/drevops/git-artifact-destination/blob/$DEPLOY_BRANCH/$TEST_FILE"
+            echo "See https://github.com/drevops/git-artifact-destination/blob/$DEPLOYED_BRANCH/$TEST_FILE"
+            rm $HOME/report--mode--force-push.txt
 
       - run:
-          name: Demonstration of deployment in 'branch' mode.
+          name: Update the test file to simulate changes in the source repository.
           command: |
-            TEST_FILE="test-file-branch-circleci-$(date "+%Y%m%d-%H%M%S").txt"
-            touch $TEST_FILE
+            sleep 1
 
+            echo "Deployment 2 for branch ${CIRCLE_BRANCH}" >> $TEST_FILE
+            date "+%Y%m%d-%H%M%S" >> $TEST_FILE
+
+      - run:
+          name: Deployment 2
+          command: |
             vendor/bin/robo artifact \
               git@github.com:drevops/git-artifact-destination.git \
-              --branch=mode-branch-circleci--[branch] \
-              --mode=branch \
-              --report=$HOME/report-mode-branch.txt \
-              --push
+              --branch=mode--force-push--circleci--[branch] \
+              --mode=force-push \
+              --report=$HOME/report--mode--force-push.txt \
+              --push \
+              --debug
 
-            DEPLOY_BRANCH=$(sed -n 's/Remote branch://p' $HOME/report-mode-branch.txt | sed 's/ //g')
-            echo "Deployed to $DEPLOY_BRANCH"
+            DEPLOYED_BRANCH=$(sed -n 's/Remote branch://p' $HOME/report--mode--force-push.txt | sed 's/ //g')
+            echo "Deployed to $DEPLOYED_BRANCH"
             echo
-            echo "See https://github.com/drevops/git-artifact-destination/blob/$DEPLOY_BRANCH/$TEST_FILE"
+            echo "See https://github.com/drevops/git-artifact-destination/blob/$DEPLOYED_BRANCH/$TEST_FILE"
+
+
+  # Demonstration of deployment in 'branch' mode.
+  # Note that by design, pushing into the same branch will result in the failure
+  # of the second push. This is because the mode is intended to create a new
+  # branch per artifact deployment.
+  deploy-branch:
+    <<: *container_config
+    steps:
+      - attach_workspace:
+          at: /workspace
+      - add_ssh_keys:
+          fingerprints:
+            - *deploy_ssh_fingerprint
+      - *step_setup_git
+      - checkout
+
+      # Test file will have a consistent name between deployments, but
+      # the contents will be added to on each deployment to simulate
+      # changes in the source repository.
+      # Since each deployment in this mode creates a new branch, the test file
+      # will be pushed to a new branch each time and won't be updated in
+      # existing branches.
+      - run:
+          name: Prepare test file.
+          command: |
+            TEST_FILE="test-file--branch--circleci--${CIRCLE_BRANCH}.txt"
+            echo "Deployment 1 for branch ${CIRCLE_BRANCH}" >> $TEST_FILE
+            date "+%Y%m%d-%H%M%S" >> $TEST_FILE
+
+      - run:
+          name: Deployment 1
+          command: |
+            vendor/bin/robo artifact \
+              git@github.com:drevops/git-artifact-destination.git \
+              --branch=mode--branch--circleci--[branch]--[timestamp:Y-m-d] \
+              --mode=branch \
+              --report=$HOME/report--mode--branch.txt \
+              --push \
+              --debug
+
+            DEPLOYED_BRANCH=$(sed -n 's/Remote branch://p' $HOME/report--mode--branch.txt | sed 's/ //g')
+            echo "Deployed to $DEPLOYED_BRANCH"
+            echo
+            echo "See https://github.com/drevops/git-artifact-destination/blob/$DEPLOYED_BRANCH/$TEST_FILE"
+            rm $HOME/report--mode--branch.txt
+
+      - run:
+          name: Update the test file to simulate changes in the source repository.
+          command: |
+            echo "Deployment 2 for branch ${CIRCLE_BRANCH}" >> $TEST_FILE
+            date "+%Y%m%d-%H%M%S" >> $TEST_FILE
+
+      - run:
+          name: Deployment 2 - same branch
+          command: |
+            vendor/bin/robo artifact \
+              git@github.com:drevops/git-artifact-destination.git \
+              --branch=mode--branch--circleci--[branch]--[timestamp:Y-m-d_H] \
+              --mode=branch \
+              --report=$HOME/report--mode--branch.txt \
+              --push \
+              --debug \
+              && { echo "Expected to fail as repeated pushes to the same branch are not allowed, but succeeded" >&2; exit 1; } || echo "Failed as expected"
+
+      - run:
+          name: Deployment 2 - new branch
+          command: |
+            vendor/bin/robo artifact \
+              git@github.com:drevops/git-artifact-destination.git \
+              --branch=mode--branch--circleci--[branch]--[timestamp:Y-m-d_H-M] \
+              --mode=branch \
+              --report=$HOME/report--mode--branch.txt \
+              --push \
+              --debug \
+              && { echo "Expected to fail but succeeded" >&2; exit 1; } || echo "Failed as expected"
+
+            DEPLOYED_BRANCH=$(sed -n 's/Remote branch://p' $HOME/report--mode--branch.txt | sed 's/ //g')
+            echo "Deployed to $DEPLOYED_BRANCH"
+            echo
+            echo "See https://github.com/drevops/git-artifact-destination/blob/$DEPLOYED_BRANCH/$TEST_FILE"
 
 workflows:
   version: 2
   main:
     jobs:
       - build
-      - deploy:
+      - deploy-force-push:
+          requires:
+            - build
+      - deploy-branch:
           requires:
             - build
